openapi: "3.0.0"
info:
  version: 0.1.0
  title: LNI 4.0 Testbed Edge Management Implementation View
  
  description: >-
    ## Legal Disclaimer 
    
    ### © Copyright 2021  Labs Network Industrie 4.0
    
    Permission is hereby granted, free of charge, to any person obtaining a copy of this specifications and associated documentation files (the “Specification”), to deal in the Specification without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Specification, and to permit persons to whom the Specification is furnished to do so, subject to the following conditions.
    The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Specification.
    THIS SPECIFICATION IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SPECIFICATION OR THE USE OR OTHER DEALINGS IN THE SPECIFICATION.
servers:
  - url: http://url/

tags:
  - name: Edge Asset Management
    description: Manage assets (i.e. devices, applications) in the edge management system directory
  - name: Asset Management
    description: Manage assets (i.e. devices, applications) directly    
  - name: Parameter Handling 
    description: (Functional View, ch. 5.4.2) 
  - name: Deployment Functions
    description: (Functional View, ch. 5.4.3) The Deployment of entities (applications) encompasses the initial installation and configuration of the application in question.


paths:
  /assets:
    get:
      summary: retrieve current asset directory content
      operationId: listAssets
      tags:
        - Edge Asset Management
      parameters:        
      - name: authorization
        in: header
        description: Access token / Key token
        required: true
        schema:
          type: string
      - name: organisationId
        in: query
        description: The id property defines the unique id of type integer
        required: true
        schema:
          minimum: 1
          type: integer
      - name: deviceType
        in: query
        description: Device types
        schema:
          type: string
          enum:
          - standard
          - sensorEDGE
      - name: page
        in: query
        description: min(1), null and empty values are not allowed
        schema:
          minimum: 1
          type: integer
          default: 1
      - name: limit
        in: query
        description: min(1) / max is set by config pageEntries, null and empty values
          are not allowed
        schema:
          maximum: 5000
          minimum: 1
          type: integer
          default: 10
      - name: sortBy
        in: query
        description: Sort by "name" or other resource property, null not allowed
        schema:
          type: string
          default: id
      - name: sortOrder
        in: query
        description: valid - "asc" and "desc", null and empty string not allowed
        schema:
          type: string
          default: asc
          enum:
          - asc
          - desc
      responses:
        '200':
          description: A paged array of assets
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Assets"
              examples:
                fieldDevice:
                  value:
                    DeviceClass: fieldDevice
                    Manufacturer: Murrelektronik
                    Model: MVK PN FDI6/3 FDO2/1 DIO4 IOL2 IRT PP
                    ProductCode: 55510
                    HardwareRevision: 1.0
                    SoftwareRevision: 2.0.1
                    SerialNumber: DE987654321
                    ProductInstanceUri: "https://shop.murrelektronik.com/55510/"
                    applicationSpecificTag: "***"
                    shortDescription: "This is the world best IO-Link-Master ;-)"
                    geolocation:
                    sysUpTime:
                edgeDevice:
                  value:  
                    DeviceClass: edgeDevice                  
                    Manufacturer: EdgeVendor GmbH
                    ProductCode: EG-123456789
                    Model: Edge Gateway
                    HardwareRevision: 1.2
                    SoftwareRevision: 3.2.1
                    SerialNumber: DE987654321                    
                edgeApp:
                  value:  
                    DeviceClass: edgeApp                  
                    Manufacturer: AppVendor Inc
                    Model: Asset Management                    
                    ProductCode: PROD-123456
                    SoftwareRevision: 1.0.0                      
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: register a notification
      operationId: registerNotification
      tags:
        - Edge Asset Management
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
                
  /assets/register:
    post:
      summary: register a asset to a tenant or organisation within the edge management system.     
      description: related to Functional View "5.1.1.2  Edge Device Detection". When an asset is detected, the EMS is informed. This command allows to register the asset. 
      operationId: assetsregister
      tags:
        - Edge Asset Management
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /apps/deploy:
    post:
      summary: deploy an application to an edge device within the edge management system.     
      description: related to Functional View "???".  
      operationId: appregister
      tags:
        - Edge Asset Management
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /tree:
    get:
      summary: retrieve structural and api information of a single addressed asset
      operationId: getAPI
      tags:
        - Asset Management
      responses:
        '200':
          description: returns the structural interface specification of the addressed asset
          content:
            application/json:    
              examples:
                fieldDevice:
                  value:

                edgeDevice:
                  value:  
                   
                edgeApp:
                  value:  
                  
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"                  
  /identity:
    get:
      summary: retrieve identity of a single addressed asset
      operationId: getIdentity
      tags:
        - Asset Management
      responses:
        '200':
          description: returns the identification nameplate of the addressed asset
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/AssetIdentification"
              examples:
                fieldDevice:
                  value:
                    DeviceClass: fieldDevice
                    Manufacturer: Murrelektronik
                    Model: MVK PN FDI6/3 FDO2/1 DIO4 IOL2 IRT PP
                    ProductCode: 55510
                    HardwareRevision: 1.0
                    SoftwareRevision: 2.0.1
                    SerialNumber: DE987654321
                    ProductInstanceUri: "https://shop.murrelektronik.com/55510/"
                    applicationSpecificTag: "***"
                    shortDescription: "This is the world best IO-Link-Master ;-)"
                    geolocation:
                    sysUpTime:
                edgeDevice:
                  value:  
                    DeviceClass: edgeDevice                  
                    Manufacturer: EdgeVendor GmbH
                    ProductCode: EG-123456789
                    Model: Edge Gateway
                    HardwareRevision: 1.2
                    SoftwareRevision: 3.2.1
                    SerialNumber: DE987654321                    
                edgeApp:
                  value:  
                    DeviceClass: edgeApp                  
                    Manufacturer: AppVendor Inc
                    Model: Asset Management                    
                    ProductCode: PROD-123456
                    SoftwareRevision: 1.0.0                      
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"    
  /picture:
    get:
      summary: retrieve picture image of a single addressed asset
      operationId: getImage
      tags:
        - Asset Management
      responses:
        '200':
          description: returns an image of the addressed asset
          content:
              image/png:
                schema: 
                  type: string
                  format: binary                   
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"                            
components:
  schemas:
    AssetIdentification:
      type: object
      required:
        - DeviceClass
        - Manufacturer
        - ManufacturerUri                  
        - Model                  
        - ProductCode                    
        - productInstanceUri
        - onBoardedAt
      properties:
        DeviceClass:          # identifies the asset type
          type: string
          enum:
           - edgeApp
           - edgeDevice
           - fieldDevice
        Manufacturer:         # vendorName
          type: string
        ManufacturerUri:      # vendorUrl
          type: string                    
        Model:                # productName
          type: string                    
        ProductCode:          # productId
          type: string
        HardwareRevision:     # hardwareRevision
          type: string
        SoftwareRevision:     # softwareRevision
          type: string
        SerialNumber:         # serialNumber
          type: string   
        ProductInstanceUri:   # AssetId
          type: string  
        ManualUrl:            # Link to manual
          type: string                     
        sysName:              # DNS HostName, SNMP: sysName, PROFINET: nameOfStation, IO-Link: deviceAlias
          type: string                    
        sysLocation:          # description of the hosts's location (i.e. an address).
          type: string  
        sysContact:           # contact data of the responsible person or organization (i.e. an email address).
          type: string 
        onBoardedAt:          # date/time when the asset has first appeared.
          type: string
          description: onBoardedAt
          format: date-time          
        geolocation:          # physical location of the assset.
          required:
          - latitude
          - longitude
          type: object
          properties:
            longitude:
              type: string
            latitude:
              type: string

    Assets:
      type: array
      items:
        $ref: "#/components/schemas/AssetIdentification"
        
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
