openapi: "3.0.0"
info:
  version: 0.1.0
  title: Implementation View
servers:
  - url: http://url/v1

tags:
  - name: Discovery Service
    description: Discovery and Directory Service
  - name: Edge Asset Management
    description: Manage assets (i.e. devices, applications) in the edge management system directory
  - name: Parameter Handling 
    description: tbd    

paths:
  /deviceId/assets:
    get:
      summary: retrieve current asset directory content
      operationId: listAssets
      tags:
        - Discovery Service
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of asset
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Assets"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: register a notification
      operationId: registerNotification
      tags:
        - Discovery Service
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /assets/register:
    post:
      summary: register a asset to a tenant or organisation within the edge management system.     
      description: related to Functional View "5.1.1.2	Edge Device Detection". When an asset is detected, the EMS is informed. This command allows to register the asset. 
      operationId: assetsregister
      tags:
        - Edge Asset Management
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /apps/deploy:
    post:
      summary: deploy an application to an edge device within the edge management system.     
      description: related to Functional View "???".  
      operationId: appregister
      tags:
        - Edge Asset Management
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Asset:
      type: object
      required:
        - id
        - Model
      properties:
        DeviceClass:
          type: string
        Manufacturer:
          type: string
        Model:
          type: string
        ProductCode:
          type: string
    Assets:
      type: array
      items:
        $ref: "#/components/schemas/Asset"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
